name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up gem, bundle, and install bundle dependencies
        uses: ./.github/actions/build
      - name: Build with Jekyll
        run: bundle exec jekyll build